services:
  app:
    image: dorm-app:latest
    build: .
    container_name: dorm
    ports:
      - "8080:8080"
    restart: no
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    build: ./mysql
    container_name: dorm-db
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: ${TZ}
    volumes:
      - ./data:/docker-entrypoint-initdb.d
      - dorm-db:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD" ]
      interval: 5s
      timeout: 10s
      retries: 10

volumes:
  dorm-db: